default['hadoop-BAM-release-jar'] =   'http://sourceforge.net/projects/hadoop-bam/files/latest/download'
default['hadoop-BAM-repo']        =   'git://git.code.sf.net/p/hadoop-bam/code'
default['hadoop-BAM-version']     =   '5.1'
default['tmp']                    =   '/tmp/hadoop-BAM'
default['install_dir']            =   '/opt'
